# ---------------- UI CONFIG ---------------- #
PLOT_TOLERANCE = 3
UI_TICK_RATE = 0.0000001
DRAW_MUDDLE_POINTS = False
DRAW_GENERATION_POINTS = False

# -------------- GENETIC CONFIG -------------- #
CROSSOVER_POSSIBILITY = 0.7
MUTATION_POSSIBILITY = 0.3
INITIAL_POPULATION = 15
CHROMOSOME_LENGTH = 16
GENOME_LEN = [8, 8]
LOWER_BOUND = []
UPPER_BOUND = []
TARGET_TOLERANCE = 0.001
MAX_GENERATION = 20
ALPHA_REPLACEMENT = 0.5
N_PTS_CROSSOVER = 10
