# ---------------- UI CONFIG ---------------- #
PLOT_TOLERANCE = 3
UI_TICK_RATE = 0.00001

# -------------- GENETIC CONFIG -------------- #
CROSSOVER_POSSIBILITY = 0.8
MUTATION_POSSIBILITY = 0.2
INITIAL_POPULATION = 20
CHROMOSOME_LENGTH = 32
GENOME_LEN = [16, 16]
LOWER_BOUND = []
UPPER_BOUND = []
TARGET_TOLERANCE = 0.001
