# ---------------- UI CONFIG ---------------- #
PLOT_TOLERANCE = 3
UI_TICK_RATE = 0
DRAW_MUDDLE_POINTS = False
DRAW_GENERATION_POINTS = False
DRAW_BEST_POINT = False

# -------------- GENETIC CONFIG -------------- #
CROSSOVER_POSSIBILITY = 0.85
MUTATION_POSSIBILITY = 0.15
# Can be None
INITIAL_POPULATION = 10
# Can be None
CHROMOSOME_LENGTH = 8 * 3
# Can be []
GENOME_LEN = [8, 8, 8]
# Can be []
LOWER_BOUND = []
# Can be []
UPPER_BOUND = []
TARGET_TOLERANCE = 0.01
MAX_GENERATION = 20
ALPHA_REPLACEMENT = 0.1
N_PTS_CROSSOVER = 3
